# PRACTICE PROBLEMS ON STRING & LIST


**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**
**<font color='red'>[Solve all the tasks sequentially]</font>**


### Task 1
Write a python program that will take a number as an input and check whether the number is Awesome or not. If the number is Awesome, it prints True, otherwise False.

**Awesome number**: a number where every digit is less than its immediate left digit is called an Awesome number. A single-digit number cannot be an awesome number(e.g. 5421 is an Awesome number.)

==========================================================

**Sample Input1:**\
976321\
**Sample Output1:**\
True

==========================================================

**Sample Input2:**\
9766321\
**Sample Output2:**\
False

==========================================================

**Sample Input3:**\
9\
**Sample Output3:**\
False

==========================================================

**Sample Input4:**\
78\
**Sample Output4:**\
False

==========================================================

**Sample Input5:**\
87\
**Sample Output4:**\
True


In [2]:
#TODO
number = int(input())
length = len(str(number))
numList = list()

for i in range(1, length + 1):
    numList.append(number // (10**(length-i)))
    number %= 10**(length-i)

awesome_state = True
for i in range(len(numList)-1):
    if not(numList[i] > numList[i+1]):
        awesome_state = False
        break
if len(numList) == 1:
    awesome_state = False

print(awesome_state)

9
False


### Task 2

Write a python program that will take list of numbers(integer) as an input from the user and print whether the number is Awesome or not.

==========================================================

**Sample Input1:**\
[976321, 321, 9763221, 9742, 876, 3211]\
**Sample Output1:**\
976321 is an awesome number.\
321 is an awesome number.\
9763221 is a not-so-awesome number.\
9742 is an awesome number.\
876 is an awesome number.\
3211 is a not-so-awesome number.

==========================================================

**Sample Input2:**\
[97821, 97210, 979210]\
**Sample Output2:**\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.


In [4]:
#TODO
valid_list = input()
valid_list = valid_list[1:-1].split(', ')

for i in range(len(valid_list)):
    number = int(valid_list[i])
    length = len(valid_list[i])
    numList = list()

    for j in range(1, length + 1):
        numList.append(number // (10**(length-j)))
        number %= 10**(length-j)

    awesome_state = True
    for j in range(len(numList)-1):
        if not(numList[j] > numList[j+1]):
            awesome_state = False
            break

    if awesome_state is True and len(numList) > 1:
        print(valid_list[i] + " is an awesome number.")
    else:
        print(valid_list[i] + " is a not-so-awesome number.")


[976321, 321, 9763221, 9742, 876, 3211]
976321 is an awesome number.
321 is an awesome number.
9763221 is a not-so-awesome number.
9742 is an awesome number.
876 is an awesome number.
3211 is a not-so-awesome number.


### Task 3


Write a python program that will take a string as input from the user where each number is separated by a comma. Then gets the numbers from the given string and removes all extra spaces. Stores the clean numbers in a list and prints it.

==========================================================

**Hints:** For obtaining the numbers from the string, use split(). For cleaning the data, use strip().

==========================================================

**Sample Input1:**

"97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210 "

**Sample Output1:**

Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]

==========================================================

**Sample Input2:**

"976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211"

**Sample Output2:**

Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]

==========================================================

**Sample Input3:**

"976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742"

**Sample Output3:**

Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]


In [8]:
#TODO
string = input()
numList = list()

temp = str()
for i in range(len(string)):
    if 48 <= ord(string[i]) <= 57:
        if i == len(string) - 1:
            temp += string[i]
            numList.append(int(temp))
        else:
            temp += string[i]
    elif string[i] == ",":
        numList.append(int(temp))
        temp = str()

print("Data after cleaning:", numList)

976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]


### Task 4

Write a python program that will take a list of numbers(integer) as an input from the user and does the following.
* counts the number of valid, invalid, and duplicate numbers and prints these to the user.
* stores the valid and invalid numbers in a list format and prints these to the user. You need to make sure that a number is stored only Once.\
  **Valid numbers:** A number with a minimum length of 4 and a maximum length of 6 is considered to be valid for this assignment.
* Calculate and print the percentage of valid numbers, invalid numbers, and duplicate numbers to the user. 

==========================================================

**Hints:** Use membership operator in and not in for checking the duplicates. For calculating the percentage, count the numbers of a particular number type.

==================================================


**Sample Input1:**\
[97821, 1, 97210, 963, 979210, 979210]\
**Sample Output1:**\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [97821, 97210, 979210]\
Invalid number count: 2\
Invalid numbers in list: [1, 963]\
Duplicate number count: 1\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 33.333333333333336\
Duplicate number percentage(%): 16.666666666666668\
\================================================


**Sample Input2:**\
[976321, 321, 9763221, 9742, 876, 3211]\
**Sample Output2:**\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 0\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 50.0\
Duplicate number percentage(%): 0.0\
\================================================

**Sample Input3:**\
[976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
**Sample Output3:**\
================================================\
Total numbers present in the given string: 8\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 2\
================================================\
Valid number percentage(%): 37.5\
Invalid number percentage(%): 37.5\
Duplicate number percentage(%): 25.0\
\================================================


In [26]:
# using "in", "not in" conditions:
string = input()
string = string[1:-1]
numList = list()

temp = str()
for i in range(len(string)):
    if 48 <= ord(string[i]) <= 57:
        if i == len(string) - 1:
            temp += string[i]
            numList.append(temp)
        else:
            temp += string[i]
    elif string[i] == ",":
        numList.append(temp)
        temp = str()

valid_count, invalid_count, dup_count = [0, 0, 0]
invalid_list, valid_list, dup_list = [[], [], []]

for i in range(len(numList)):
    if 4 <= len(numList[i]) <= 6:
        if int(numList[i]) not in valid_list:
            valid_list.append(int(numList[i]))
            valid_count += 1
        else:
            dup_list.append(numList[i])
            dup_count += 1
    else:
        if int(numList[i]) not in invalid_list:
            invalid_list.append(int(numList[i]))
            invalid_count += 1
        else:
            dup_list.append(numList[i])
            dup_count += 1

print(f"================================================\nTotal numbers present in the given string:  {len(numList)}\nValid number count:  {valid_count}\nValid numbers in list:  {valid_list}\nInvalid number count:  {invalid_count}\nInvalid numbers in list:  {invalid_list}\nDuplicate number count:  {dup_count}\n================================================\nValid number percentage:  {(valid_count/len(numList)) * 100} %\nInvalid number percentage:  {(invalid_count/len(numList)) * 100} %\nDuplicate number percentage:  {(dup_count/len(numList)) * 100} %")

[976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]
Total numbers present in the given string:  8
Valid number count:  3
Valid numbers in list:  [976321, 9742, 3211]
Invalid number count:  3
Invalid numbers in list:  [321, 9763221, 876]
Duplicate number count:  2
Valid number percentage:  37.5 %
Invalid number percentage:  37.5 %
Duplicate number percentage:  25.0 %


In [12]:
# using Loop and "==", "!=" conditions:
string = input()
numList = string[1:-1].split(", ")

valid_count, invalid_count, dup_count = [0, 0, 0]
invalid_list, valid_list, dup_list = [[], [], []]

for i in range(len(numList)):
    if 4 <= len(numList[i]) <= 6:
        for j in range(len(valid_list)):
            if int(numList[i]) == valid_list[j]:
                dup_list.append(numList[i])
                dup_count += 1
                break
        else:
            valid_list.append(int(numList[i]))
            valid_count += 1
    else:
        for j in range(len(invalid_list)):
            if int(numList[i]) == invalid_list[j]:
                dup_list.append(numList[i])
                dup_count += 1
                break
        else:
            invalid_list.append(int(numList[i]))
            invalid_count += 1

print(f"================================================\nTotal numbers present in the given string:  {len(numList)}\nValid number count:  {valid_count}\nValid numbers in list:  {valid_list}\nInvalid number count:  {invalid_count}\nInvalid numbers in list:  {invalid_list}\nDuplicate number count:  {dup_count}\n================================================\nValid number percentage:  {(valid_count/len(numList)) * 100} %\nInvalid number percentage:  {(invalid_count/len(numList)) * 100} %\nDuplicate number percentage:  {(dup_count/len(numList)) * 100} %")

[976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]
Total numbers present in the given string:  8
Valid number count:  3
Valid numbers in list:  [976321, 9742, 3211]
Invalid number count:  3
Invalid numbers in list:  [321, 9763221, 876]
Duplicate number count:  2
Valid number percentage:  37.5 %
Invalid number percentage:  37.5 %
Duplicate number percentage:  25.0 %


### Task 5

Write a python program that will take a list of numbers(integer) as an input from the user. Then stores the valid numbers, the sum of digits, and multiplication of the digits for each valid number in a list where each number is the 1st element of the list, the sum of digits is the 2nd element of the list and the multiplication of digits is the 3rd element of the list. Finally, print the nested list to the user. 

==========================================================

**Sample Input1:**\
[97821, 97210, 979210]\
**Sample Output1:**\
Data [number, sum of digits, product of digits]:\
[[97821, 27, 1008], [97210, 19, 0], [979210, 28, 0]]

================================================

**Sample Input2:**\
[976321, 9742, 3211, 30987]\
**Sample Output2:**\
Data [number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9742, 22, 504], [3211, 7, 6], [30987, 27, 0]]

================================================

**Sample Input3:**\
[976321, 9640, 3211]\
**Sample Output3:**\
Data [number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]

================================================


In [35]:
#TODO
string = input()
numList = string[1:-1].split(", ")

nested_list = list()

for i in range(len(numList)):
    summ = 0
    product = 1
    if 4 <= len(numList[i]) <= 6:
        for j in range(len(numList[i])):
            summ += int(numList[i][j])
            product *= int(numList[i][j])
        nsp_list = [int(numList[i]), summ, product]
        nested_list.append(nsp_list)

print(f"Data [number, sum of digits, product of digits]:\n{nested_list}")

[976321, 321, 9763221, 9742, 876, 3211]
Data [number, sum of digits, product of digits]:
[[976321, 28, 2268], [9742, 22, 504], [3211, 7, 6]]


### Task 6 (Merger of Task1-Task5)

Write a python program that will take a string as input from the user where each number is separated by a comma. The numbers must have a minimum length of 4 and a maximum length of 6 to be considered valid for this assignment. Then, you need to complete the following. 

* Part1: get the numbers from the given string, remove all extra spaces. (clean the data). Print the clean data to the user.
* Part2: count the number of valid, invalid, and duplicate numbers and print these to the user.
* Part3: store the valid and invalid numbers in a list format and print these to the user. You need to make sure that a number is stored only Once.
* Part4: Calculate and print the percentage of valid numbers, invalid numbers, and duplicate numbers to the user.
* Part5: store the valid numbers, the sum of digits, and multiplication of the digits for each valid number in a list where each number is the 1st element of the list, the sum of digits is the 2nd element of the list and the multiplication of digits is the 3rd element of the list. Finally, print the nested list to the user.
* Part6: Check whether the valid numbers are Awesome or not.
  **Awesome number:** a number where every digit is less than its immediate left digit is called is an awesome number. (e.g. 5421 is an awesome number).

==============================================================================================

**Sample Input1:**\
"97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210 "\
**Sample Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [97821, 97210, 979210]\
Invalid number count: 2\
Invalid numbers in list: [1, 963]\
Duplicate number count: 1\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 33.333333333333336\
Duplicate number percentage(%): 16.666666666666668\
================================================\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data of valid numbers:\
[number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
\^\_\^ Awesomeness checking of the Valid numbers \^\_\^\
976321 is an awesome number.\
9640 is an awesome number.\
3211 is a not-so-awesome number.\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

==============================================================================================


**Sample Input2:**\
"976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211"\
**Sample Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
================================================\
Total numbers present in the given string: 6\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 0\
================================================\
Valid number percentage(%): 50.0\
Invalid number percentage(%): 50.0\
Duplicate number percentage(%): 0.0\
================================================\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data of valid numbers:\
[number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
\^\_\^ Awesomeness checking of the Valid numbers \^\_\^\
976321 is an awesome number.\
9640 is an awesome number.\
3211 is a not-so-awesome number.\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


==============================================================================================

**Sample Input3:**\
"976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742"\
**Sample Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
================================================\
Total numbers present in the given string: 8\
Valid number count: 3\
Valid numbers in list: [976321, 9742, 3211]\
Invalid number count: 3\
Invalid numbers in list: [321, 9763221, 876]\
Duplicate number count: 2\
================================================\
Valid number percentage(%): 37.5\
Invalid number percentage(%): 37.5\
Duplicate number percentage(%): 25.0\
================================================\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data of valid numbers:\
[number, sum of digits, product of digits]:\
[[976321, 28, 2268], [9640, 19, 0], [3211, 7, 6]]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
\^\_\^ Awesomeness checking of the Valid numbers \^\_\^\
976321 is an awesome number.\
9640 is an awesome number.\
3211 is a not-so-awesome number.\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

In [38]:
#TODO

####################################################################
### Data Cleaning ###
####################################################################

string = input()
numList = string.split(",")
for i in range(len(numList)):
    numList[i] = numList[i].strip()

cleaned_List = list()
for item in numList:
    cleaned_List.append(int(item))

####################################################################
### Valid, Invalid, Duplicate Identifier ###
####################################################################

valid_count, invalid_count, dup_count = [0, 0, 0]
invalid_list, valid_list, dup_list = [[], [], []]

for i in range(len(numList)):
    if 4 <= len(numList[i]) <= 6:
        if int(numList[i]) not in valid_list:
            valid_list.append(int(numList[i]))
            valid_count += 1
        else:
            dup_list.append(int(numList[i]))
            dup_count += 1
    else:
        if int(numList[i]) not in invalid_list:
            invalid_list.append(int(numList[i]))
            invalid_count += 1
        else:
            dup_list.append(int(numList[i]))
            dup_count += 1

####################################################################
### Number, Sum, Product Finder & Nested List ###
####################################################################

nested_list = list()
for i in range(len(valid_list)):
    summ = 0
    product = 1
    nsp_list = list()
    current_number = str(valid_list[i])
    for j in range(len(current_number)):
        summ += int(current_number[j])
        product *= int(current_number[j])
    nsp_list = [valid_list[i], summ, product]
    nested_list.append(nsp_list)


### ==================================================================================
### ==================================================================================
print(f"Data after cleaning: {cleaned_List}\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n================================================\nTotal numbers present in the given string: {len(numList)}\nValid number count: {valid_count}\nValid numbers in list: {valid_list}\nInvalid number count: {invalid_count}\nInvalid numbers in list: {invalid_list}\nDuplicate number count: {dup_count}\n================================================\nValid number percentage: {(valid_count/len(numList)) * 100} %\nInvalid number percentage: {(invalid_count/len(numList)) * 100} %\nDuplicate number percentage: {(dup_count/len(numList)) * 100} %\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nData of valid numbers:\n[number, sum of digits, product of digits]:\n{nested_list}\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
### ==================================================================================
### ==================================================================================


####################################################################
print("^_^ Awesomeness checking of the Valid numbers ^_^")
####################################################################

for i in range(len(valid_list)):
    number = valid_list[i]
    length = len(str(valid_list[i]))
    check_list = list()

    for j in range(1, length + 1):
        check_list.append(number // (10 ** (length - j)))
        number %= 10**(length-j)

    awesome_state = True
    for j in range(len(check_list) - 1):
        if not(check_list[j] > check_list[j + 1]):
            awesome_state = False
            break

    if awesome_state == True:
        print(str(valid_list[i]) + " is an awesome number.")
    else:
        print(str(valid_list[i]) + " is a not-so-awesome number.")
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")

976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Total numbers present in the given string: 8
Valid number count: 3
Valid numbers in list: [976321, 9742, 3211]
Invalid number count: 3
Invalid numbers in list: [321, 9763221, 876]
Duplicate number count: 2
Valid number percentage: 37.5 %
Invalid number percentage: 37.5 %
Duplicate number percentage: 25.0 %
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data of valid numbers:
[number, sum of digits, product of digits]:
[[976321, 28, 2268], [9742, 22, 504], [3211, 7, 6]]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
^_^ Awesomeness checking of the Valid numbers ^_^
976321 is an awesome number.
9742 is an awesome number.
3211 is a not-so-awesome number.
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
