# PRACTICE PROBLEMS ON FUNCTION

### Task 1
Write a function called **check_awesomeness** that takes a number as an argument and Checks whether the number is Awesome or not. If the number is Awesome, it returns True, otherwise False.
 
**Awesome number:** a number where every digit is less than its immediate left digit is called an Awesome number. A single digit number cannot be an awesome number(e.g. 5421 is an Awesome number).

==========================================================

**Function Call1:**\
check_awesomeness(976321)\
**Output1:**\
True

==========================================================

**Function Call2:**\
check_awesomeness(9766321)\
**Output2:**\
False

==========================================================

**Function Call3:**\
check_awesomeness(9)\
**Output3:**\
False

==========================================================

**Function Call4:**\
check_awesomeness(78)\
**Output4:**\
False

==========================================================

**Function Call5:**\
check_awesomeness(87)\
**Output4:**\
True

In [3]:
#todo
def check_awesomeness(num):
    number = num
    length = len(str(number))
    num_list = list()
    for j in range(1, length + 1):
        num_list.append(number // (10**(length-j)))
        number %= 10**(length-j)

    awesome_state = True
    for j in range(len(num_list)-1):
        if not(num_list[j] > num_list[j+1]):
            awesome_state = False
            break

    if len(num_list) == 1:
        return False
    else:
        return awesome_state


print(check_awesomeness(98765))
print(check_awesomeness(87))
print(check_awesomeness(9))
print(check_awesomeness(9766321))

True
True
False
False


### Task 2
Write a function called **check_awesome** that takes a list of numbers(integer) as an argument and Prints whether the number is Awesome or not.

**<font color='red'>Must reuse the check_awesomeness() function.</font>**

==========================================================

**Function Call1:**\
check_awesome([976321, 321, 9763221, 9742, 876, 3211])\
**Output1:**\
976321 is an awesome number.\
321 is an awesome number.\
9763221 is a not-so-awesome number.\
9742 is an awesome number.\
876 is an awesome number.\
3211 is a not-so-awesome number.

==========================================================

**Function Call2:**\
check_awesome([97821, 97210, 979210])\
**Output2:**\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.

In [4]:
#todo
def check_awesome(num_list):

    for i in range(len(num_list)):
        number = num_list[i]
        length = len(str(num_list[i]))
        check_list = list()

        for j in range(1, length + 1):
            check_list.append(number // (10**(length-j)))
            number %= 10**(length-j)

        awesome_state = True
        for j in range(len(check_list)-1):
            if not(check_list[j] > check_list[j+1]):
                awesome_state = False
                break

        if awesome_state is True and len(check_list) > 1:
            print(num_list[i], "is an awesome number.")
        else:
            print(num_list[i], "is a not-so-awesome number.")


check_awesome([976321, 321, 9763221, 9742, 876, 3211])

976321 is an awesome number.
321 is an awesome number.
9763221 is a not-so-awesome number.
9742 is an awesome number.
876 is an awesome number.
3211 is a not-so-awesome number.


### Task 3
Write a function called **find_max_min** that takes a list of numbers(integers) as a  function parameter and finds the numbers with maximum and minimum value. Then returns these two numbers as a **tuple** and prints the results using tuple unpacking in the function call according to the given format. Both valid and invalid numbers should be considered for finding maximum and minimum.<font color='red'>[Must use tuple packing & unpacking] </font>

==========================================================

**Function Call1:**\
find_max_min([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output1:**\
Returned value from find_max_min() is: (9763221, 321)\
Number with maximum value is 9763221\
Number with minimum value is 321

==========================================================

**Function Call2:**\
find_max_min([97821, 1, 97210, 963, 979210, 979210])\
**Output2:**\
Returned value from find_max_min() is: (979210, 1)\
Number with maximum value is 979210\
Number with minimum value is 1

In [5]:
#todo
def find_max_min(num_list):
    max_val = num_list[0]
    min_val = num_list[0]
    for i in range(len(num_list)):
        if num_list[i] >= max_val:
            max_val = num_list[i]
            max_index = i
        if num_list[i] <= min_val:
            min_val = num_list[i]
            min_index = i
    min_max = (max_val, min_val)
    return min_max


maximum, minimum = find_max_min([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])
print(f"Returned value from find_max_min() is: ({maximum}, {minimum})\nNumber with maximum value is {maximum}\nNumber with minimum value is {minimum}")

Returned value from find_max_min() is: (9763221, 321)
Number with maximum value is 9763221
Number with minimum value is 321


### Task 4
Write a function called **data_cleaning** that takes a string as an argument. Then gets the numbers from the given string and removes all extra spaces. Stores the clean numbers (integers) in a list and **returns** it to the function call.

==========================================================

**Function Call1:**\
data_cleaning("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]

==========================================================

**Function Call2:**\
data_cleaning("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]

==========================================================

**Function Call3:**\
data_cleaning("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]

In [6]:
#todo
def data_cleaning(called_string):
    num_list = list()
    temp = str()
    for i in range(len(called_string)):
        if 48 <= ord(called_string[i]) <= 57:
            if i == len(called_string) - 1:
                temp += called_string[i]
                num_list.append(int(temp))
            else:
                temp += called_string[i]
        elif called_string[i] == ",":
            num_list.append(int(temp))
            temp = str()
    return num_list


print(f"Data after cleaning: {data_cleaning('976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742')}")

Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]


### Task 5
Write a function called **grouping_data** that takes  a list of numbers(integers) as a  function parameter and creates a dictionary where "valid", "invalid", and "duplicate" are the keys. The numbers that fall in those categories are the values.

**Valid & Invalid numbers:** A number with a minimum length of 4 and a maximum length of 6 is considered to be valid for this assignment. All the other numbers are considered to be Invalid numbers.\
**Duplicate numbers:** If a number appears more than once in the List, then that is a duplicate number. Both valid and invalid numbers can be duplicates.

Lastly, print the dictionary **inside the function** and **return** the dictionary to the function call.

==========================================================

**Function Call1:**\
grouping_data([97821, 1, 97210, 963, 979210, 979210])\
**Output1:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]


==========================================================

**Function Call2:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211])\
**Output2:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]


==========================================================

**Function Call3:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output3:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]



In [7]:
# todo
def grouping_data(num_list):

    invalid_list, valid_list, dup_list = [[], [], []]

    for i in range(len(num_list)):
        if 4 <= len(str(num_list[i])) <= 6:
            if num_list[i] not in valid_list:
                valid_list.append(num_list[i])
            else:
                dup_list.append(num_list[i])
        else:
            if num_list[i] not in invalid_list:
                invalid_list.append(num_list[i])
            else:
                dup_list.append(num_list[i])

    valid_invalid_dup_dict = dict()
    valid_invalid_dup_dict["valid"] = valid_list
    valid_invalid_dup_dict["invalid"] = invalid_list
    valid_invalid_dup_dict["duplicate"] = dup_list
    print(
        f"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\nData dictionary printing inside the function:\n{valid_invalid_dup_dict}\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    return valid_invalid_dup_dict


returned_val = grouping_data(
    [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])
print(
    f"Returned dictionary: {returned_val}\nValid number list obtained from the dictionary: {returned_val['valid']}")


XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}
Valid number list obtained from the dictionary: [976321, 9742, 3211]


### Task6
Write a function called **individual_line_data** that takes a string as an argument. This function should do the following. 
* clean and prints the data.
* group the numbers in a dictionary obtained from the given string.
* check whether the **valid numbers** are awesome or not.
* find and print the maximum and minimum number among the **valid numbers** obtained from the given string.

*Hints:*\
You MUST reuse data_cleaning(), grouping_data(), check_awesome() and find_max_min() functions. 

==========================================================

**Function Call1:**\
individual_line_data("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
\^\_\^ Awesomeness checking of the Valid numbers \^\_\^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210




**Function Call2:**\
individual_line_data("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
\^\_\^ Awesomeness checking of the Valid numbers \^\_\^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211



**Function Call3:**\
individual_line_data("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
\^\_\^ Awesomeness checking of the Valid numbers \^\_\^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211


In [8]:
#todo
def individual_line_data(input_string):

    number_list = data_cleaning(input_string)
    print(f"Data after cleaning: {number_list}")

    returned_dict = grouping_data(number_list)
    print(f"Returned dictionary: {returned_dict}\nValid number list obtained from the dictionary: {returned_dict['valid']}")

    print("=================================================\n^_^ Awesomeness checking of the Valid numbers ^_^")
    check_awesome(returned_dict["valid"])
    print("=================================================")

    max_num, min_num = find_max_min(returned_dict["valid"])
    print(f"Returned value from find_max_min() is: ({max_num}, {min_num})\nNumber with maximum value is {max_num}\nNumber with minimum value is {min_num}")


individual_line_data("976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742")

Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}
Valid number list obtained from the dictionary: [976321, 9742, 3211]
^_^ Awesomeness checking of the Valid numbers ^_^
976321 is an awesome number.
9742 is an awesome number.
3211 is a not-so-awesome number.
Returned value from find_max_min() is: (976321, 3211)
Number with maximum value is 976321
Number with minimum value is 3211


### Task 7
Write a function called **number_analysis** that takes a list of strings as an argument and 
analyse those strings. \
**<font color='red'>Must reuse the individual_line_data() function.</font>**

In [9]:
#todo
def number_analysis(list_of_strings):
    for i in range(len(list_of_strings)):
        print(f"######### Printing data for line no: 0{i+1} #########")
        individual_line_data(list_of_strings[i])
        print("\n\n")

### Task 8
Run the following block of code for seeing the final output of this Problem.

**Output:**
######### Printing data for line no: 01 #########\
Data after cleaning: [321, 976322]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976322], 'invalid': [321], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976322], 'invalid': [321], 'duplicate': []}\
Valid number list obtained from the dictionary: [976322]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976322 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976322, 976322)\
Valid number with maximum value is 976322\
Valid number with minimum value is 976322

&emsp; 

######### Printing data for line no: 02 #########\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210

&emsp; 

######### Printing data for line no: 03 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211

&emsp;

######### Printing data for line no: 04 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211

In [10]:
lines_of_data = [
    "321 ,   976322",
    "97821, 1 , 97210, 963, 979210 , 979210",
    "976321, 321 ,   9763221, 9742, 876, 3211",
    "976321, 321 ,   9763221, 9742, 876, 3211, 976321, 9742"
]

number_analysis(lines_of_data)

######### Printing data for line no: 01 #########
Data after cleaning: [321, 976322]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [976322], 'invalid': [321], 'duplicate': []}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Returned dictionary: {'valid': [976322], 'invalid': [321], 'duplicate': []}
Valid number list obtained from the dictionary: [976322]
^_^ Awesomeness checking of the Valid numbers ^_^
976322 is a not-so-awesome number.
Returned value from find_max_min() is: (976322, 976322)
Number with maximum value is 976322
Number with minimum value is 976322



######### Printing data for line no: 02 #########
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}
XXXXXXXXXXXXXXXXXXXXXXXXXXX